name: JP Writes Code
description: Things I find interesting
url: http://japesinator.github.io
safe: True
lsi: false
encoding: UTF-8
markdown: redcarpet
highlighter: true
github: www.github.com/japesinator
about: I am a high school student in the midwest who likes math, computers, and other interesting things
urls:
    - text: github
      url: https://github.com/japesinator
    - text: email
      url: mailto:jp@mail.writes.co.de
    - text: twitter
      url: https://twitter.com/japesinator
    - text: about
      url: /about
